const products = [
  {
    id: 1,
    name: "Royal Blue Mysore Silk Saree",
    description: "Elegant Mysore silk with zari border",
    main_price: 2999,
    discounted_price: 999,
    image: "../src/assets/Rectangle.png",
    category: "Mysore silk",
    quantity:0,
  },
  {
    id: 2,
    name: "Traditional Kanchipuram Silk",
    description: "Pure Kanchipuram with golden zari",
    main_price: 4999,
    discounted_price: 2999,
    image: "../src/assets/Rectangle.png",
    category: "Kanchipuram silk",
    quantity:0,
  },
  {
    id: 3,
    name: "Soft Cotton Silk Saree",
    description: "Comfortable cotton silk for daily wear",
    main_price: 7999,
    discounted_price: 4999,
    image: "../src/assets/Rectangle.png",
    category: "Cotton silk",
    quantity:0,
  },
  {
    id: 4,
    name: "Red Banarasi Silk Saree",
    description: "Rich traditional Banarasi design",
    main_price: 1999,
    discounted_price: 999,
    image: "../src/assets/Rectangle.png",
    category: "Banarasi silk",
    quantity:0,
  },
  {
    id: 5,
    name: "Golden Tussar Silk Saree",
    description: "Handloom tussar silk with unique texture",
    main_price: 3999,
    discounted_price: 1999,
    image: "../src/assets/Rectangle.png",
    category: "Tussar silk",
    quantity:0,
  },
  {
    id: 6,
    name: "Royal Blue Mysore Silk Saree",
    description: "Elegant Mysore silk with zari border",
    main_price: 2999,
    discounted_price: 999,
    image: "../src/assets/Rectangle.png",
    category: "Mysore silk",
    quantity:0,
  },
  {
    id: 7,
    name: "Traditional Kanchipuram Silk",
    description: "Pure Kanchipuram with golden zari",
    main_price: 4999,
    discounted_price: 2999,
    image: "../src/assets/Rectangle.png",
    category: "Kanchipuram silk",
    quantity:0,
  },
  {
    id: 8,
    name: "Soft Cotton Silk Saree",
    description: "Comfortable cotton silk for daily wear",
    main_price: 7999,
    discounted_price: 4999,
    image: "../src/assets/Rectangle.png",
    category: "Cotton silk",
    quantity:0,
  },
  {
    id: 9,
    name: "Red Banarasi Silk Saree",
    description: "Rich traditional Banarasi design",
    main_price: 1999,
    discounted_price: 999,
    image: "../src/assets/Rectangle.png",
    category: "Banarasi silk",
    quantity:0,
  },
  {
    id: 10,
    name: "Golden Tussar Silk Saree",
    description: "Handloom tussar silk with unique texture",
    main_price: 3999,
    discounted_price: 1999,
    image: "../src/assets/Rectangle.png",
    category: "Tussar silk",
    quantity:0,
  },
];

export default products;