const products = [
  {
    id: 1,
    name: "Royal Blue Mysore Silk Saree 1",
    description: "Elegant Mysore silk with zari border",
    main_price: 2999,
    discounted_price: 999,
    image1: "../src/assets/Rectangle.png",
    image2: "../src/assets/saree_image2.svg",
    image3: "../src/assets/saree_image3.svg",
    image4: "../src/assets/saree_image4.svg",
    category: "Mysore silk",
    product_code: "BJDC4547",
    saree_length: 6.2,
    wash_and_care: "Dry clean",
    // quantity:0,
  },
  {
    id: 2,
    name: "Traditional Kanchipuram Silk 1",
    description: "Pure Kanchipuram with golden zari",
    main_price: 4999,
    discounted_price: 2999,
    image2: "../src/assets/Rectangle.png",
    image1: "../src/assets/saree_image2.svg",
    image3: "../src/assets/saree_image3.svg",
    image4: "../src/assets/saree_image4.svg",
    category: "Kanchipuram silk",
    product_code: "BJDC4547",
    saree_length: 6.2,
    wash_and_care: "Dry clean",
    // quantity:0,
  },
  {
    id: 3,
    name: "Soft Cotton Silk Saree 1",
    description: "Comfortable cotton silk for daily wear",
    main_price: 7999,
    discounted_price: 4999,
    image3: "../src/assets/Rectangle.png",
    image2: "../src/assets/saree_image2.svg",
    image1: "../src/assets/saree_image3.svg",
    image4: "../src/assets/saree_image4.svg",
    category: "Cotton silk",
    product_code: "BJDC4547",
    saree_length: 6.2,
    wash_and_care: "Dry clean",
    // quantity:0,
  },
  {
    id: 4,
    name: "Red Banarasi Silk Saree 1",
    description: "Rich traditional Banarasi design",
    main_price: 1999,
    discounted_price: 999,
    image4: "../src/assets/Rectangle.png",
    image2: "../src/assets/saree_image2.svg",
    image3: "../src/assets/saree_image3.svg",
    image1: "../src/assets/saree_image4.svg",
    category: "Banarasi silk",
    product_code: "BJDC4547",
    saree_length: 6.2,
    wash_and_care: "Dry clean",
    // quantity:0,
  },
  {
    id: 5,
    name: "Golden Tussar Silk Saree 1",
    description: "Handloom tussar silk with unique texture",
    main_price: 3999,
    discounted_price: 1999,
    image1: "../src/assets/Rectangle.png",
    image2: "../src/assets/saree_image2.svg",
    image3: "../src/assets/saree_image3.svg",
    image4: "../src/assets/saree_image4.svg",
    category: "Tussar silk",
    product_code: "BJDC4547",
    saree_length: 6.2,
    wash_and_care: "Dry clean",
    // quantity:0,
  },
  {
    id: 6,
    name: "Royal Blue Mysore Silk Saree 2",
    description: "Elegant Mysore silk with zari border",
    main_price: 2999,
    discounted_price: 999,
    image2: "../src/assets/Rectangle.png",
    image1: "../src/assets/saree_image2.svg",
    image3: "../src/assets/saree_image3.svg",
    image4: "../src/assets/saree_image4.svg",
    category: "Mysore silk",
    product_code: "BJDC4547",
    saree_length: 6.2,
    wash_and_care: "Dry clean",
    // quantity:0,
  },
  {
    id: 7,
    name: "Traditional Kanchipuram Silk 2",
    description: "Pure Kanchipuram with golden zari",
    main_price: 4999,
    discounted_price: 2999,
    image3: "../src/assets/Rectangle.png",
    image2: "../src/assets/saree_image2.svg",
    image1: "../src/assets/saree_image3.svg",
    image4: "../src/assets/saree_image4.svg",
    category: "Kanchipuram silk",
    product_code: "BJDC4547",
    saree_length: 6.2,
    wash_and_care: "Dry clean",
    // quantity:0,
  },
  {
    id: 8,
    name: "Soft Cotton Silk Saree 2",
    description: "Comfortable cotton silk for daily wear",
    main_price: 7999,
    discounted_price: 4999,
    image4: "../src/assets/Rectangle.png",
    image2: "../src/assets/saree_image2.svg",
    image3: "../src/assets/saree_image3.svg",
    image1: "../src/assets/saree_image4.svg",
    category: "Cotton silk",
    product_code: "BJDC4547",
    saree_length: 6.2,
    wash_and_care: "Dry clean",
    // quantity:0,
  },
  {
    id: 9,
    name: "Red Banarasi Silk Saree 2",
    description: "Rich traditional Banarasi design",
    main_price: 1999,
    discounted_price: 999,
    image1: "../src/assets/Rectangle.png",
    image2: "../src/assets/saree_image2.svg",
    image3: "../src/assets/saree_image3.svg",
    image4: "../src/assets/saree_image4.svg",
    category: "Banarasi silk",
    product_code: "BJDC4547",
    saree_length: 6.2,
    wash_and_care: "Dry clean",
    // quantity:0,
  },
  {
    id: 10,
    name: "Golden Tussar Silk Saree 2",
    description: "Handloom tussar silk with unique texture",
    main_price: 3999,
    discounted_price: 1999,
    image2: "../src/assets/Rectangle.png",
    image1: "../src/assets/saree_image2.svg",
    image3: "../src/assets/saree_image3.svg",
    image4: "../src/assets/saree_image4.svg",
    category: "Tussar silk",
    product_code: "BJDC4547",
    saree_length: 6.2,
    wash_and_care: "Dry clean",
    // quantity:0,
  },
  {
    id: 11,
    name: "Royal Blue Mysore Silk Saree 3",
    description: "Elegant Mysore silk with zari border",
    main_price: 2999,
    discounted_price: 999,
    image3: "../src/assets/Rectangle.png",
    image2: "../src/assets/saree_image2.svg",
    image1: "../src/assets/saree_image3.svg",
    image4: "../src/assets/saree_image4.svg",
    category: "Mysore silk",
    product_code: "BJDC4547",
    saree_length: 6.2,
    wash_and_care: "Dry clean",
    // quantity:0,
  },
  {
    id: 12,
    name: "Traditional Kanchipuram Silk 3",
    description: "Pure Kanchipuram with golden zari",
    main_price: 4999,
    discounted_price: 2999,
    image4: "../src/assets/Rectangle.png",
    image2: "../src/assets/saree_image2.svg",
    image3: "../src/assets/saree_image3.svg",
    image1: "../src/assets/saree_image4.svg",
    category: "Kanchipuram silk",
    product_code: "BJDC4547",
    saree_length: 6.2,
    wash_and_care: "Dry clean",
    // quantity:0,
  },
  {
    id: 13,
    name: "Soft Cotton Silk Saree 3",
    description: "Comfortable cotton silk for daily wear",
    main_price: 7999,
    discounted_price: 4999,
    image1: "../src/assets/Rectangle.png",
    image2: "../src/assets/saree_image2.svg",
    image3: "../src/assets/saree_image3.svg",
    image4: "../src/assets/saree_image4.svg",
    category: "Cotton silk",
    product_code: "BJDC4547",
    saree_length: 6.2,
    wash_and_care: "Dry clean",
    // quantity:0,
  },
  {
    id: 14,
    name: "Red Banarasi Silk Saree 3",
    description: "Rich traditional Banarasi design",
    main_price: 1999,
    discounted_price: 999,
    image2: "../src/assets/Rectangle.png",
    image1: "../src/assets/saree_image2.svg",
    image3: "../src/assets/saree_image3.svg",
    image4: "../src/assets/saree_image4.svg",
    category: "Banarasi silk",
    product_code: "BJDC4547",
    saree_length: 6.2,
    wash_and_care: "Dry clean",
    // quantity:0,
  },
  {
    id: 15,
    name: "Golden Tussar Silk Saree 3",
    description: "Handloom tussar silk with unique texture",
    main_price: 3999,
    discounted_price: 1999,
    image3: "../src/assets/Rectangle.png",
    image2: "../src/assets/saree_image2.svg",
    image1: "../src/assets/saree_image3.svg",
    image4: "../src/assets/saree_image4.svg",
    category: "Tussar silk",
    product_code: "BJDC4547",
    saree_length: 6.2,
    wash_and_care: "Dry clean",
    // quantity:0,
  },
  {
    id: 16,
    name: "Royal Blue Mysore Silk Saree 4",
    description: "Elegant Mysore silk with zari border",
    main_price: 2999,
    discounted_price: 999,
    image4: "../src/assets/Rectangle.png",
    image2: "../src/assets/saree_image2.svg",
    image3: "../src/assets/saree_image3.svg",
    image1: "../src/assets/saree_image4.svg",
    category: "Mysore silk",
    product_code: "BJDC4547",
    saree_length: 6.2,
    wash_and_care: "Dry clean",
    // quantity:0,
  },
  {
    id: 17,
    name: "Traditional Kanchipuram Silk 4",
    description: "Pure Kanchipuram with golden zari",
    main_price: 4999,
    discounted_price: 2999,
    image1: "../src/assets/Rectangle.png",
    image2: "../src/assets/saree_image2.svg",
    image3: "../src/assets/saree_image3.svg",
    image4: "../src/assets/saree_image4.svg",
    category: "Kanchipuram silk",
    product_code: "BJDC4547",
    saree_length: 6.2,
    wash_and_care: "Dry clean",
    // quantity:0,
  },
  {
    id: 18,
    name: "Soft Cotton Silk Saree 4",
    description: "Comfortable cotton silk for daily wear",
    main_price: 7999,
    discounted_price: 4999,
    image2: "../src/assets/Rectangle.png",
    image1: "../src/assets/saree_image2.svg",
    image3: "../src/assets/saree_image3.svg",
    image4: "../src/assets/saree_image4.svg",
    category: "Cotton silk",
    product_code: "BJDC4547",
    saree_length: 6.2,
    wash_and_care: "Dry clean",
    // quantity:0,
  },
  {
    id: 19,
    name: "Red Banarasi Silk Saree 4",
    description: "Rich traditional Banarasi design",
    main_price: 1999,
    discounted_price: 999,
    image3: "../src/assets/Rectangle.png",
    image2: "../src/assets/saree_image2.svg",
    image1: "../src/assets/saree_image3.svg",
    image4: "../src/assets/saree_image4.svg",
    category: "Banarasi silk",
    product_code: "BJDC4547",
    saree_length: 6.2,
    wash_and_care: "Dry clean",
    // quantity:0,
  },
  {
    id: 20,
    name: "Golden Tussar Silk Saree 4",
    description: "Handloom tussar silk with unique texture",
    main_price: 3999,
    discounted_price: 1999,
    image4: "../src/assets/Rectangle.png",
    image2: "../src/assets/saree_image2.svg",
    image3: "../src/assets/saree_image3.svg",
    image1: "../src/assets/saree_image4.svg",
    category: "Tussar silk",
    product_code: "BJDC4547",
    saree_length: 6.2,
    wash_and_care: "Dry clean",
    // quantity:0,
  },
];

export default products;